name: Auto Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Adjust the Python version as needed
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable with PyInstaller and spec file
      run: |
        python -m PyInstaller script.spec 
    - name: List output directory
      run: ls dist/

    - name: Create first ZIP file with exe and additional resources
      run: |
        zip -r Vector24-ADDVNAME-amd64-win.zip dist/Vector24.exe app.log config.json positions.json startup.mp3

    - name: Upload outer ZIP file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: final-zip-package
        path: Vector24-ADDVNAME-amd64-win.zip
