name: Package only configuration files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Adjust the Python version as per your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable with PyInstaller and spec file
      run: |
        pyinstaller your_script.spec  # Use the spec file for the build

    - name: List output directory
      run: ls dist/

    - name: Create ZIP file with required resources (excluding exe)
      run: |
        zip -r packaged_resources.zip app.log config.json positions.json startup.mp3

    - name: Upload ZIP file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: packaged-resources
        path: packaged_resources.zip
